# Framework for running automated tests on OSB using Travis-CI, see https://github.com/OpenSourceBrain/osb-model-validation
# Still in development, subject to change without notice!!

language: python
python: 2.7

env:
    - OMV_ENGINE=jNeuroML

install: 
    
    # Install OMV
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation
       
    
    # Install libNeuroML (development version) & dependencies
    - cd
    - git clone https://github.com/NeuralEnsemble/libNeuroML.git
    - cd libNeuroML
    - git checkout development
    - python setup.py install
    - cd $TRAVIS_BUILD_DIR
    

    # Install pyNeuroML. Also installs a number of dependencies
    - pip install pyNeuroML


script:
    - cd ./NeuroML2/

    # Test analysis of channels using pynml-channelanalysis from PyNeuroML
    - pynml-channelanalysis -temperature 34  -minV -55  -maxV 80  -duration 600  -clampBaseVoltage -55  -clampDuration 580  -stepTargetVoltage 10  -erev 50  -nogui  ./ca_boyle.channel.nml
    - pynml-channelanalysis -temperature 34  -minV -55  -maxV 80  -duration 600  -clampBaseVoltage -55  -clampDuration 580  -stepTargetVoltage 10  -erev -55 -nogui  ./k_fast.channel.nml
    - pynml-channelanalysis -temperature 34  -minV -55  -maxV 80  -duration 600  -clampBaseVoltage -55  -clampDuration 580  -stepTargetVoltage 10  -erev -55 -nogui  ./k_slow.channel.nml

    # Run all tests (usually .test.*) using OMV (see https://github.com/OpenSourceBrain/osb-model-validation)
    - omv all -V
    
    
